<div class="featuresTab mainContainer clearfix">
    <div class="messageContent clearfix">
        <div class="shadowSeparator clearfix">
            <div class="shadowSeparatorBox clearfix">

            </div><!--End shadowSeparatorBox-->
            <div class="shadowSeparatorBox clearfix">

            </div><!--End shadowSeparatorBox-->
        </div><!--End shadowSeparator-->
    </div>
</div><!--End featuresTab -->
<script type="text/javascript">
    $(document).ready(function() {

        $(".more").shorten({
            "showChars" : 200
        });

    });
</script>
