<?php $emailForm = $this->emailForm; ?>
<?php $subscriptionForm = $this->subscriptionForm; ?>
<div class="paymentsTab mainContainer clearfix">
    <div class="messageContent clearfix">
        <div class="shadowSeparator clearfix">
            <div class="shadowSeparatorBox clearfix">
                <form action="<?php echo $this->baseUrl() . "/payment/email"?>" name="paypal_email" method="post">
                    <div class="leftCol">
                        <div class="formRow clearfix">
                            <h1><?php echo $this->translate('PayPal Email:'); ?></h1>
                            <div class="formRow"> <label class="title">E-mail address:</label><?php echo $emailForm->paypal_email; ?></div>
                            <div class="formRow"><?php echo $this->translate('Enter your email address that is associated with your paypal account'); ?></div>
                        </div><!--End formRow-->
                    </div>
                    <div class="buttonRow clearfix floatRight"><?php echo $emailForm->saveemail; ?></div><!--End buttonRow-->
                </form>

            <div class="shadowSeparatorBoxSmall clearfix">
            </div><!--End shadowSeparatorBox-->
                <div class="shadowSeparator clearfix"></div>
                <form action="<?php echo $this->baseUrl() . "/payment/subscribe"?>" name="subscribe" method="post">
                    <div class="leftCol">
                        <h1><?php echo $this->translate('Subscription:'); ?></h1>
                        <div class="formRow clearfix">
                            <!--<label class="title"><?php /*echo $this->translate('Date from:'); */?></label>
                            <div class="formElem"><?php /*echo $subscriptionForm->date_from; */?></div>-->
                            <label class="title"><?php echo $this->translate('Period:'); ?></label>
                            <div class="formRow"><?php echo $subscriptionForm->period; ?></div>
                            <div class="formRow"><?php echo $this->translate('By subscribing for 8 months period, you\'ll get 4 additional months for free'); ?></div>
                        </div><!--End formRow-->
                    </div>

                    <div class="buttonRow floatRight clearfix"><?php echo $subscriptionForm->subscribe; ?><input type="button" value="unsubscribe" class="button"></div><!--End buttonRow-->
                </form>

            </div><!--End shadowSeparatorBox-->
        </div><!--End shadowSeparator-->
    </div>
</div><!--End featuresTab -->
<script type="text/javascript">
    $(document).ready(function() {

        $(".more").shorten({
            "showChars" : 200
        });

    });
</script>
