<div class="messages">
    <?php echo $this->confirmFlash;?>
</div>
<div class="alertBlock">

</div>

<div class="row-fluid layout-body clearfix">

    <div class="homeLeftCol">
        <fieldset>
            <legend class="strictFont">ABOUT AIMYA</legend>
            <div class = "shadowSeparator"></div>
            <div class="mainText">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.</div>
        </fieldset>
        <div class = "galleryMain"></div>
    </div>

   <div class="homeRightCol regBlock">

        <!-- REGISTRATION -->
        <div id="registrationFormHolder">
            <form id="signUp" action="/user/registration/" name="signUp" method="post" class="strictFont">
                <fieldset>
                    <legend class="strictFont">REGISTER</legend>
                         <div class = "shadowSeparator"></div>
                    <div class='buttonBar'>
                        <?php echo $this->reg['type'] . '<br>';?>
                    </div>
                    <ul>
                        <li><?php echo $this->reg['firstname'];?></li>
                        <li><?php echo $this->reg['lastname'];?></li>
                        <li><?php echo $this->reg['gender'];?></li>
                        <li><?php echo $this->reg['username'];?></li>
                        <li><?php echo $this->reg['email'];?></li>
                        <li><?php echo $this->reg['password'];?></li>
                        <li><?php echo $this->reg['password2'];?></li>
                      <li> <?php echo $this->reg['signup'];?></li>
                    </ul>
                    <div class ="twitterIcon"></div><div class ="facebookIcon"></div><div class = "linkedInIcon"></div>
                </fieldset>
            </form>

        </div>

       <!-- END of REGISTRATION -->
    </div>

</div>



