<?php

if(Zend_Registry::isRegistered('username')){
    $username = Zend_Registry::get('username');
}else{
    $identity = Zend_Auth::getInstance()->getStorage()->read();
    $userModel = new Application_Model_DbTable_Users();
    $username = $userModel->getUser($identity->id);
    $username = "{$username['firstname']} {$username['lastname']}";
    Zend_Registry::set('username', $username);
}
echo '<div class="accountWrapper">
<div class = "leftBlockProfile">' . $username .'</div>'.

    $this->layout()->content.

    '</div>';