<?php
//information in left block of account:
//  firstname, lastname, avatar, member since
$identity = Zend_Auth::getInstance()->getStorage()->read();
$userModel = new Application_Model_DbTable_Users();
$profileModel = new Application_Model_Profile();

$username = $userModel->getUser($identity->id);
$avatarPath = $profileModel->getAvatarPath($identity->id); //path to avatar
$memberSince = substr($username['created_at'], 0, 4);

if (Zend_Registry::isRegistered('username')) {
    $username = Zend_Registry::get('username');
} else {

    $username = "{$username['firstname']} {$username['lastname']}";
    Zend_Registry::set('username', $username);
}
?>
<div class="accountWrapper row-fluid no-space">

    <div class="leftBlockProfile span2">

        <h3> <?php echo $username;?></h3>
        Member since <?php echo $memberSince;?><br>
        <img src="<?php echo $avatarPath;?>">
        No rate
        <div class="leftNavigation">
            <?php
            echo $this->navigation()
                ->menu()
                ->setMaxDepth(0)
                ->setUlClass('nav nav-tabs nav-stacked')
                ->render(new Aimya_Navigation($this->navigation()->findAllBy('tag', 'leftMenu', true)));
            ?>
        </div>
    </div>

    <div class="mainBlockProfile span10">
        <?php echo $this->layout()->content; ?>
    </div>
</div>