<script type="text/javascript">
    $('input[type="checkbox"]').checkRadio({
        wrapperClass: 'checkboxWrapper',
        chekedClass: 'checked'
    });
</script>

<div class="availabilityTab clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <div class = "topBox clearfix">
                <h1><?php echo $this->translate('i am available');?>:</h1>

                <div class="dateZoneBlock">
                    <span class ="dateUTC"><?php echo $this->translate('You are currently in UTC');?> <?php echo $this->user['timezone']; ?></span>
                    <p><span class ="dateHint"><?php echo $this->translate('to change time zone go to General tab');?></span></p>
                </div>
            </div>
            <div class = "bottomBox clearfix">
                <?php
                $daysOfWeek = array('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun');
                $daysOfWeekFull = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
                ?>
                <form method='post' name='availability' action="<?php echo $this->baseUrl()?>/account/availability/">
                    <table class='table table-striped table-condensed'>
                        <?php
                        $day = 'checkbox';
                        $availableFrom = 'selectFrom';
                        $availableTo = 'selectTo';
                        foreach ($daysOfWeek as $index => $value) {
                            $$availableFrom = 'from' . $daysOfWeek[$index];
                            $$day = 'checkbox' . $daysOfWeek[$index];

                            $$availableTo = 'to' . $daysOfWeek[$index];
                            echo "<tr><td>{$this->availabilityForm->$checkbox}<div class='dayCheckbox'></div></td><td>{$this->translate($daysOfWeekFull[$index])}</td><td>{$this->translate('from')}</td><td><div class='styledSelect'>{$this->availabilityForm->$selectFrom}</div></td> <td>{$this->translate('to')}</td> <td><div class='styledSelect'>{$this->availabilityForm->$selectTo}</div></td></td></tr>";
                        }

                        ?>
                    </table>
                    <div class="buttonRow clearfix"><?php  echo $this->availabilityForm->save;?></div><!--End buttonRow-->
                </form>
            </div>
        </div>
    </div>
    <script type='text/javascript'>
        $(document).ready(function() {
            var pathName = $('#current_url').val();

            $("#save").click(updateAvailaibility);

        });
    </script>
</div>
