<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Basic</a></li>

        <li><a href="/account/services">Service Details</a></li>
        <li><a href="/account/notifications">Notifications/Account Settings</a></li>
        <li><a href="/account/users">Users</a></li>
        <li><a href="/account/resume">My Resume</a></li>
        <li><a href="/account/metrics">My Metrics</a></li>
    </ul>
    <div id="tabs-1">
        <div class="profile">
            <form method="post" name="profile" action="" enctype="multipart/form-data">
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo $this->profile->avatar; ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo $this->profile->firstname; ?>
                        <?php echo $this->profile->lastname; ?>
                        <?php echo $this->profile->birthday; ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <?php echo $this->profile->language; ?>
                        <?php echo $this->profile->email; ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <?php echo $this->profile->timezone; ?>
                        <?php echo $this->profile->username; ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo $this->profile->add_info; ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12 offset3">
                        <?php echo $this->profile->saveProfile; ?>
                    </div>
                </div>
            </form>
        </div>
        <!--End PROFILE  -->
    </div>

    <div id="tabs-3">
    </div>
    <div id="tabs-4">
    </div>
    <div id="tabs-5">
    </div>
    <div id="tabs-6">
    </div>
</div>



<?php print_r($this->errors); ?>