<div class = "profile">
    <form method="post" name="profile" action = "" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="span12">
             <?php echo $this->profile->avatar; ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->profile->firstname; ?>
            <?php echo $this->profile->lastname; ?>
            <?php echo $this->profile->birthday; ?>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->profile->language; ?>
            <?php echo $this->profile->email; ?>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->profile->timezone; ?>
            <?php echo $this->profile->initials; ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->profile->intro; ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->profile->saveProfile; ?>
        </div>
    </div>
    </form>
</div><!--End PROFILE  -->

<?php print_r($this->errors) ;?>