
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">GENERAL</a></li>
        <?php if($this->role !== '1'){echo  '<li><a href="/account/services">SERVICE DETAILS</a></li>';}?>
        <li><a href="/account/requestservices">REQUEST SERVICES</a></li>
        <li><a href="/account/availability">AVAILABILITY</a></li>
        <li><a href="/account/notifications">NOTIFICATIONS/ACCOUNT SETTINGS</a></li>
        <li><a href="/account/users">USERS</a></li>
        <li><a href="/account/metrics">MY METRICS</a></li>
    </ul>
    <div id="tabs-1">
        <div class="profile">
            <div class="firstSeparator"></div>
            <h3>YOUR BASIC INFORMATION:</h3>
            <form method="post" name="profile" action="" enctype="multipart/form-data">
                <div class="profileAvatar"><div class="profileAvaImg"><img src="<?php echo $this->avatarPath;?>" alt="avatar">
                    ​</div>
                    <?php echo $this->profile->avatar; ?>
                    <input type="button" id="uploadAvatar" value="UPLOAD" />
                    <input type="button" id="removeAvatar" value="DELETE" />
                </div>

                <ul>


                    <li> <span>First Name:</span>  <?php echo $this->profile->firstname; ?></li>

                    <li> <span>Last Name:</span> <?php echo $this->profile->lastname; ?></li>

                    <li> <span>Gender:</span> <?php echo $this->profile->gender; ?></li>

                    <li> <span>Login:</span> <?php echo $this->profile->username; ?></li>

                    <li> <span>DOB:</span> <?php echo $this->profile->birthday; ?> <span class="add-on"></span> </li>

                    <li> <span>Language:</span> <?php echo $this->profile->language; ?></li>

                    <li> <span>Email:</span> <?php echo $this->profile->email; ?></li>

                    <li> <span>Time Zone:</span><?php echo $this->profile->timezone; ?></li>
                    <li> <div class="introduceLabel">INTRODUCE YOURSELF:</div></li>
                    <li> <?php echo $this->profile->add_info; ?></li>
                </ul>

                <div class="row-fluid">
                    <div class="span12 offset3">
                        <?php echo $this->profile->saveProfile; ?>
                    </div>
                </div>
            </form>
        </div>
        <!--End PROFILE  -->
    </div>

    <div id="tabs-3">
    </div>
    <div id="tabs-4">
    </div>
    <div id="tabs-5">
    </div>

</div>



<?php print_r($this->errors); ?>