<div class="shadowSeparator clearfix">
    <div class="shadowSeparatorBox clearfix">
        <div class="metricItem">
            <h1><?php echo $this->translate('users')?></h1>
            <div class="formRow">
                <span class="head"><?php echo $this->translate('Total Users linked My Account'); ?>:</span>
                <?php echo $this->totalPeersCount?>
            </div>
            <div class="formRow">
                <span class="head"><?php echo $this->translate('Total Users connected with this month'); ?>:</span>
                <?php echo $this->monthPeersCount?>
            </div>
        </div>
        <div class="shadowSeparatorBoxSmall"> </div>
        <div class="shadowSeparator"> </div>
        <div class="metricItem">
            <h1><?php echo $this->translate('income')?></h1>
            <div class="formRow">
                <span class="head"><?php echo $this->translate('Total income since becoming a member'); ?>:</span>
                <?php echo $this->totalIncome?>
            </div>
            <div class="formRow">
                <span class="head"><?php echo $this->translate('YTD income'); ?>:</span>
                <?php echo $this->yearIncome?>
            </div>
            <div class="formRow">
                <span class="head"><?php echo $this->translate('Last month\'s income'); ?>:</span>
                <?php echo $this->monthIncome?>
            </div>
        </div>
    </div>
</div>