<script type="text/javascript">
    $('input[type="checkbox"]').checkRadio({
        wrapperClass:'checkboxWrapper',
        chekedClass:'checked'
    });
</script>
<div class="notificationsTab clearfix">
    <form method='post' name='notifications' action="<?php echo $this->baseUrl()?>/account/notifications/">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <h1> I WANT TO:</h1>
            <div class = 'notificationsAlertsBlock'>
                <?php
                echo $this->notificationsForm->alert;
                ?>
            </div>
        </div>
    </div>
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <h1> CHANGE AIMYA PASSWORD:</h1>

            <div class="passwordRecoveryBlock">
                <?php echo '<span>Old Password: </span>' . $this->notificationsForm->oldPassword; ?><br>
                <?php echo '<span>New Password: </span>' . $this->notificationsForm->newPassword; ?><br>
                <?php echo '<span>Confirm New Password: </span>' . $this->notificationsForm->newPasswordConfirm; ?>
            </div>
        </div>
    </div>
    <?php
    if ($this->notificationsForm->notify) {
        echo '
        <div class="shadowSeparator clearfix">
             <div class="shadowSeparatorBox clearfix">
                <h1> I WANT TO:</h1> <div class="notificationsAlertsBlock">' . $this->notificationsForm->notify . '</div>
             </div>
        </div>';
    }
    ?>
    <div class="buttonsRow clearfix">
        <?php
        echo $this->notificationsForm->saveNotifications;
        ?>
    </div>

    </form>

</div>