<div id="tabs-2">
    <!--LIST OF SERVICES -->
    <?php foreach($this->services as $value){
    echo "<div class = 'service'>
        <div class = 'row-fluid'>
            <div class='span12'>
         {$value['lesson_category']} -
               {$value['subcategory']}
                \${$value['rate']} per
               {$value['duration']}
            </div>
        </div>
        <div class='row-fluid'>
            <div class='span12'>
                Service Description :<br>
                {$value['description']}
            </div>
        </div>
        <div class='row-fluid'>
            <div class='span12 offset4'>
            </div>
        </div>
    </div>";
}
?>

    <!-- END LIST OF SERVICES -->

    <!-- SERVICE FORM -->
    <form method="post" name="profile" action="account/services" enctype="multipart/form-data">
        <div class="row-fluid">
            <div class="span12">
                <?php echo $this->servicesForm->lesson_category; ?>
                <?php echo $this->servicesForm->subcategory; ?>
                <?php echo $this->servicesForm->rate; ?> per
                <?php echo $this->servicesForm->duration; ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <?php echo $this->servicesForm->description; ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12 offset4">
                <?php echo $this->servicesForm->saveService; ?>
            </div>
        </div>
    </form>
    <!-- END SERVICE FORM -->
</div>