<div id="tabs-2">
    <!--LIST OF SERVICES -->
    <?php foreach($this->services as $value):?>
        <div class = 'service'>
        <div class = 'row-fluid'>
            <div class='span12'>
         <?php echo $value['lesson_category'];?> -
                <?php echo $value['subcategory'];?>
                $<?php echo $value['rate'];?> per
                <?php echo $value['duration'];?>
            </div>
        </div>
        <div class='row-fluid'>
            <div class='span12'>
                Service Description :<br>
                <?php echo $value['description'];?>
            </div>
        </div>
        <div class='row-fluid'>
            <div class='span12 offset1'>
                    <input type = 'button' id = 'editService' value = 'Edit' class = 'btn' onclick ='editService(this);return false;'>
                    <input type = 'button' id = 'deleteService' value = 'Delete' class = 'btn' onclick ='deleteService(this);return false;'>
                    <input type = 'hidden' value = " <?php echo $value['id'];?>">
            </div>
        </div>
    </div>
<?php endforeach;?>
    <!-- END LIST OF SERVICES -->

    <!-- SERVICE FORM -> ADD NEW: css display:none;-->
    <div id ="addService">
        <form method="post" name="serviceDetails" action="account/services" id="serviceForm">
            <div class="row-fluid">
                <div class="span12">
                    <?php echo $this->servicesForm->lesson_category; ?>
                    <?php echo $this->servicesForm->subcategory; ?>
                    <?php echo $this->servicesForm->rate; ?> per
                    <?php echo $this->servicesForm->duration; ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <?php echo $this->servicesForm->description; ?>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span12 offset4">
                    <?php echo $this->servicesForm->saveService; ?>
                </div>
            </div>
        </form>
    </div>
    <!-- END SERVICE FORM -> ADD NEW-->
    <input type = "button" id = "addMoreServices" value = "Add More" class = "btn" onclick = "addService();">
</div>