<div class="userRelationsTab profile clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <table class="table">
                <thead>
                <tr>
                    <td> First Name</td>
                    <td> Last Name</td>
                    <td> User Name</td>
                    <td> Time Zone</td>
                    <td> Block / Delete</td>
                </tr>
                </thead>
                <tbody>
                <?php

                $url = "'{$this->baseUrl()}/account/edit'";
                if ($this->friends) {
                    foreach ($this->friends as $value) {

                        if ($value['status'] != 2) {

                            echo '<tr>
        <td>' . $value['firstname'] . '</td>
        <td>' . $value['lastname'] . '</td>
        <td>' . $value['username'] . '</td>
        <td>UTC ' . $value['timezone'] . '</td>
        <td><input type = "button" value="BLOCK" class = "button-2 block"  onclick ="blockUser(this, ' . $url . ');return false;"></div><input type = "button" value = "DELETE" class="button-2 delete" onclick="deleteUser(this, ' . $url . ');return false;"></div><input type = "hidden" value = ' . $value['id'] . '></td>
    </tr>';
                        }else{
                            echo '<tr class="blocked">
        <td>' . $value['firstname'] . '</td>
        <td>' . $value['lastname'] . '</td>
        <td>' . $value['username'] . '</td>
        <td>UTC ' . $value['timezone'] . '</td>
        <td><input type = "button" value="UNBLOCK" class = "button-2 block"  onclick ="unblockUser(this, ' . $url . ');return false;"></div><input type = "button" value = "DELETE" class="button-2 delete" onclick="deleteUser(this, ' . $url . ');return false;"></div><input type = "hidden" value = ' . $value['id'] . '></td>
    </tr>';
                        }
                    }

                }

                ?>


                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="usersAlert" id="delete-confirm" title="DELETE USER:">
    <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>By deleting user, he will
        be erased from your user list permanently. Are you sure you want to proceed?</p>
</div>

<div class="usersAlert" id="block-confirm" title="BLOCK USER:">
    <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>Block user?</p>
</div>

<div class="usersAlert" id="unblock-confirm" title="UNBLOCK USER:">
    <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>Unblock user?</p>
</div>