<div class = "userRelations">
    <div class="firstSeparator"></div>
    <table  class="table table-striped table-hover">
    <thead style="background: #ccc">
    <tr>
        <td> First Name </td>
        <td> Last Name </td>
        <td> User Name </td>
        <td> Time Zone </td>
        <td> Block/Delete </td>
    </tr>
    </thead>
    <tbody>
    <?php
    if($this->friends){
        foreach($this->friends as $value){
            echo '<tr>
        <td>'.$value['firstname'].'</td>
        <td>'.$value['lastname'].'</td>
        <td>'.$value['username'].'</td>
        <td>UTC '.'timezone'.'</td>
        <td><div class = "blockUser" onclick ="blockUser(this);return false;">Block</div><div class = "deleteUser" onclick ="deleteUser(this);return false;">Delete</div><input type = "hidden" value = '. $value['id'].'</td>
    </tr>';
        }

    }

    ?>

    </tbody>
</table>
</div>