<?php $studentLessons = $this->studentLessons; ?>
<?php echo $this->partial('partials/lesson.phtml') ?>
<div class="mainContainer userRelationsTab lesson clearfix">
    <div class="shadowSeparator clearfix">
        <div class="lessonFilterBlock clearfix">
            <div class="filters">
                <h1 class="floatLeft"> <?php echo $this->translate('display list of:') ?></h1>
                <?php echo $this->filterForm->details; ?>
                <?php echo $this->translate('from') ?><?php echo $this->filterForm->fromPeriod; ?>
                <?php echo $this->translate('to') ?><?php echo $this->filterForm->toPeriod; ?>
            </div>
            <a class="button-2 display floatRight"><?php echo $this->translate('display') ?></a>
        </div>
        <div class="shadowSeparatorBoxSmall clearfix">
            </div>
        <div class="shadowSeparator clearfix">
        </div>
        <div class="shadowSeparatorBox clearfix">
            <table class="table">
                <thead>
                <tr>
                    <td> <?php echo $this->translate('Date') ?></td>
                    <td> <?php echo $this->translate('Time') ?></td>
                    <td> <?php echo $this->translate('Focus Name') ?></td>
                    <td> <?php echo $this->translate('Video REC') ?></td>
                    <td> <?php echo $this->translate('Feedback') ?></td>
                    <td> <?php echo $this->translate('Notes') ?></td>
                </tr>
                </thead>

                <tbody>
                <?php foreach ($studentLessons as $lesson): ?>
                    <?php $date = substr($lesson['started_at'], 0, 10);
                    $time = substr($lesson['started_at'], 10);
                    ?>
                <tr>

                    <td><?php echo $date; ?></td>
                    <td><?php echo $time; ?></td>
                    <td><?php echo $lesson['focus_name']?></td>
                    <td class ="center">
                        <?php if ($lesson['video']): ?>
                        <a href="#" class="button-2 open center"><?php echo $this->translate('Open') ?></a>
                        <?php endif;?>
                    </td>
                    <td class ="center">
                        <?php if ($lesson['feedback']): ?>
                        <a href="#" class="button-2 open center"><?php echo $this->translate('Open') ?></a>
                        <?php endif;?>
                    </td>
                    <td class ="center">
                        <?php if ($lesson['notes']): ?>
                        <a href="#" class="button-2 open "><?php echo $this->translate('Open') ?></a>
                        <?php endif;?>
                    </td>
                </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>