<?php $studentLessons = $this->studentLessons; ?>
<?php echo $this->partial('partials/lesson.phtml') ?>
<div class="mainContainer userRelationsTab lesson clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <table class="table">
                <thead>
                <tr>
                    <td> <?php echo $this->translate('Date') ?></td>
                    <td> <?php echo $this->translate('Focus Name') ?></td>
                    <td> <?php echo $this->translate('Video REC') ?></td>
                    <td> <?php echo $this->translate('Feedback') ?></td>
                    <td> <?php echo $this->translate('Notes') ?></td>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($studentLessons as $lesson): ?>
                        <tr>
                            <td><?php echo $lesson['created_at']?></td>
                            <td><?php echo $lesson['focus_name']?></td>
                            <td>
                                <?php if ($lesson['video']): ?>
                                    <a href="#"><?php echo $this->translate('Open') ?></a>
                                <?php endif;?>
                            </td>
                            <td>
                                <?php if ($lesson['feedback']): ?>
                                    <a href="#"><?php echo $this->translate('Open') ?></a>
                                <?php endif;?>
                            </td>
                            <td>
                                <?php if ($lesson['notes']): ?>
                                    <a href="#"><?php echo $this->translate('Open') ?></a>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>