<?php $availableLesson = $this->availableLesson; ?>
<?php echo $this->partial('partials/lesson.phtml') ?>
<div class="mainContainer userRelationsTab lesson clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">

            <?php $bookingTable = new Application_Model_DbTable_Booking()?>
            <?php //$test = $bookingTable->isTeacher(54)?>
            <?php //var_dump($test)?>

            <?php $bookings = $this->bookingList; ?>
            <?php if (!$availableLesson): ?>
            <table class="table">
                <thead>
                <tr>
                    <td> <?php echo $this->translate('User Name') ?></td>
                    <!--<td> <?php /*echo $this->translate('Status') */?></td>-->
                    <td> <?php echo $this->translate('Date/Time') ?></td>
                    <td> <?php echo $this->translate('Focus Name') ?></td>
                    <td> <?php echo $this->translate('Video REC') ?></td>
                    <td> <?php echo $this->translate('Feedback') ?></td>
                    <td> <?php echo $this->translate('PDF Notes') ?></td>
                    <td> <?php echo $this->translate('Payment Request') ?></td>
                    <td> <?php echo $this->translate('Action') ?></td>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($bookings as $booking): ?>
                    <?php //Zend_Debug::dump($booking)?>
                <tr>
                    <td class="username">
                        <input type="hidden" id="booking_<?php echo $booking['booking']['id']?>"
                               value="<?php echo $booking['booking']['id']?>">
                        <?php echo $booking['userData']['firstname'] . ' ' . $booking['userData']['lastname']?>
                    </td>
                    <td class="startTime"><?php echo $booking['booking']['started_at']; ?></td>
                    <td class="focusName"><?php echo $booking['booking']['focus_name']; ?></td>
                    <td class="center">
                        <?php if ($booking['booking']['video']) {
                        echo '<span class ="checBoxGrey"></span>';
                    } else {
                        echo '<span class ="checBoxGrey empty"></span>';
                    } ?>
                    </td>
                    <td class="center">
                        <?php if ($booking['booking']['feedback']) {
                        echo '<span class ="checBoxGrey"></span>';
                    } else {
                        echo '<span class ="checBoxGrey empty"></span>';
                    } ?>
                    </td>
                    <td class="center">
                        <?php if ($booking['booking']['notes']) {
                        echo '<span class ="checBoxGrey"></span>';
                    } else {
                        echo '<span class ="checBoxGrey empty"></span>';
                    } ?>
                    </td>
                    <?php                         $date = gmdate("Y-m-d H:i:s");
                    $userTable = new Application_Model_DbTable_Users();
                    //                        if()
                    $userGmt = $userTable->getTimeZone($this->userId);
                    $timeZone = str_replace(':', '.', $userGmt['timezone']);
                    $timeToAdd = floatval($timeZone);

                    $dateWithUTC = gmdate("m/d/Y H:i", strtotime($date) + (($timeToAdd + 1) * 3600)); //adding timezone
                    ?>
                    <?php $user_id = $booking['userData']['id'];?>


                    <?php if ($booking['booking']['payment_status'] == '0'):?>
                    <?php if ($bookingTable->isTeacher($booking['booking']['id'], Zend_Auth::getInstance()->getIdentity()->id)): ?>

                    <?php if (strtotime($booking['booking']['started_at']) - strtotime($dateWithUTC) <= 600 && strtotime($booking['booking']['started_at']) - strtotime($dateWithUTC) > 0): ?>
                        <td class="center"><input type="button" class="button send"
                                                  onclick="payRequest(<?php echo $user_id;?>,<?php echo $booking['booking']['id'];?>, this);"
                                                  value= <?php echo $this->translate('Send'); ?>></td>
                        <?php else: ?>
                        <td class="center">waiting to send</td>
                        <?php endif; ?>

                    <?php endif; ?>
                    <?php endif; ?>

                    <?php if ($booking['booking']['booking_status'] == '1' )://BOOKING status == 1(approved) ?>
                        <?php if ($booking['booking']['payment_status'] == '1' && $bookingTable->isTeacher($booking['booking']['id'], Zend_Auth::getInstance()->getIdentity()->id))://PAYMENT status == 1(request to pay has been sent) ?>
                        <td class="center result pending">Pending</td>
                        <?php elseif ($booking['booking']['payment_status'] == '2')://PAYMENT status == 2(request  has been paid) ?>
                        <td class="center result success">Paid</td>
                        <?php endif; ?>

                            <?php if (strtotime($booking['booking']['started_at']) - strtotime($dateWithUTC) <= 600 && strtotime($booking['booking']['started_at']) - strtotime($dateWithUTC) > 0): ?>
                            <?php if($booking['booking']['payment_status'] == '1'):?>
                            <td>
                            <form method="POST" id='pay_<?php echo $booking['booking']['id'];?>'
                                  action="<?php echo $this->baseUrl() . '/payment/pay/'?>">
                                <input name="teacher_id" type="hidden" value="<?php echo $booking['userData']['id'];?>">
                                <input name="booking_id" type="hidden" value="<?php echo $booking['booking']['id'];?>">
                            <a href="#" id="<?php echo $booking['userData']['id'];?>"
                               onclick="jQuery('#pay_<?php echo $booking['booking']['id'];?>').submit()"><span
                                class="button-2 play">Pay</span></a>
                                <?php else: ?>
                            <?php echo '<td>fail</td>';?>
                                <?php endif; ?>
                            </form>
                            </td>

                        <?php endif; ?>
                        <?php endif; ?>
                        <?php if ((strtotime($booking['booking']['started_at']) - strtotime($dateWithUTC) > 600 || strtotime($booking['booking']['started_at']) - strtotime($dateWithUTC) < 0) && $booking['booking']['payment_status'] == '0'): ?>
                                <td class="center payment">waiting</td>
                            <?php endif; ?>


                    <td> <!--ACTION-->
                        <?php if ($booking['booking']['payment_status'] == '2'):

                            ?>

                            <form method="POST" id='start_session_<?php echo $booking['booking']['id'];?>'
                                  action="<?php echo $this->baseUrl() . '/lesson/setup/'?>">
                                <input name="student_id" type="hidden" value="<?php echo $booking['userData']['id'];?>">
                                <input name="booking_id" type="hidden" value="<?php echo $booking['booking']['id'];?>">
                                <?php if ($bookingTable->isTeacher($booking['booking']['id'], Zend_Auth::getInstance()->getIdentity()->id)): ?>
                                <a href="#" id="<?php echo $booking['userData']['id'];?>"
                                   onclick="jQuery('#start_session_<?php echo $booking['booking']['id'];?>').submit()"><span
                                    class="button-2 play">Start</span></a>
                                <?php else: ?>
                                <?php echo "something" ?>
                                <?php endif; ?>
                            </form>
                            <?php endif;?>
                    </td>
                </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <tr>
                <td><?php echo "You can't start new lesson because you have active lesson. Go to \"On yhe Air Tab\" to end old lesson"?></td>
            </tr>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php if (Zend_Auth::getInstance()->getIdentity()->role == 2): ?>
<script type="text/javascript">

    function startSession(id) {
        var form = $('#start_session');
        var serializedData = form.serialize();
        $('#tabs').tabs('select', 1);
        $.ajax({
            'url':$('#start_session').attr('action'),
            'data':({student_id:id}),
            //'data': serializedData,
            'dataType':'json',
            'type':'get',
            success:function (data) {
                $('#flash_element').append(data.flashObj);
            }
        });
    }
</script>
<?php elseif (Zend_Auth::getInstance()->getIdentity()->role == 1): ?>
<script type="text/javascript">
    function doAjax() {
        $.ajax({
            'url':'<?php echo $this->baseUrl() . "/lesson/join/";?>',
            'data':({student_id:3}),
            //'data': serializedData,
            'dataType':'json',
            'type':'get',
            success:function (data) {
                if (data.result == true) {
                    $('#flash_element').append(data.flashObj);
                    return false;
                } else {
                    setTimeout(doAjax, 3000);
                }
            }
        });
    }
    doAjax();
</script>
<?php endif; ?>