<?php echo $this->partial('partials/lesson.phtml')?>
<div class= "messageContent">
    <div id="flash_element">
        <?php if($this->flashObj == NULL):?>
            <h4><?php echo 'There are no any active lessons'; ?></h4>
        <?php else:?>
            <?php echo $this->flashObj; ?>
        <?php endif;?>
    </div>
</div>
<script type="text/javascript">
    function changeFlashLayout(flashType) {

        if(flashType == 1) {
           flashObf = jQuery('#flash_element');
           jQuery('.accountWrapper').hide();
           jQuery('.footer').hide();
           jQuery('body').append(flashObf);
        } else if(flashType == 0) {
            jQuery('#flash_element').remove();
            jQuery('.accountWrapper').show();
            jQuery('.footer').show();
            jQuery('.messageContent').append(flashObf);
        }

    }
</script>