<div id="lessonTabs" class="tabsHolder clearfix">
    <?php echo $this->partial('partials/lesson.phtml')?>
    <div id="flashContainer" class="mainContainer clearfix" style="width: 870px; height: 1190px">
<!--<div class= "messageContent" style="height:1190px; width:870px">-->
        <div id="flash_element" style="height:100%">
            <?php if($this->flashObj == NULL):?>
                <h4><?php echo 'There are no any active lessons'; ?></h4>
            <?php else:?>
            <script type="text/javascript">
                $(document).ready(function() {
                    var element = '<?php echo $this->flashObj; ?>';
                    $('#flash_element').html('');
                    jQuery('#page').hide();
                    jQuery('#leftBg').hide();
                    $('#flash_div').show();
                    jQuery('#flash_div').append(element);
                });

            </script>
            <?php endif;?>
        </div>
    </div>
</div>
