<div id="tabs-2">
    <?php echo "foo-2"; ?>
    <?php
        $baseLink = $this->baseLink();
    ?>
    <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://active.macromedia.com/flash4/cabs/swflash.cab#version=4,0,0,0" id="name" width="400" height="400">
        <param name="movie" value="<?php echo "{$baseLink}/flash/test4pix.swf"?>">
        <param name="quality" value="high">
        <param name="wmode" value="transparent">
        <embed name="name" src="<?php echo "{$baseLink}/flash/test4pix.swf" ?>" quality="high" wmode="transparent" width="400" height="400" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer"></embed>
    </object>
</div>