<?php echo $this->partial('partials/message.phtml') ?>
<?php $message = $this->message; ?>
<?php $sender = $this->sender; ?>
<?php $form = $this->form; ?>
    <div class="messageTab">
        <div class="shadowSeparator clearfix">
            <div class="shadowSeparatorBox clearfix">

                <form method="post" action="<?php echo $this->baseUrl()?>/message/forward/">

                    <div class="sendMessageBox clearfix">
                        <div class="formRow clearfix">
                            <div class="label messageForwardInbox"><?php echo $this->translate('to');?>:</div> <?php echo $form->message_id->setValue(Zend_Controller_Front::getInstance()->getRequest()->getParam('message_id'));?>
                            <?php echo $form->username;?></div>
                        <div class="formRow clearfix">
                            <div class="label"><?php echo $this->translate('subject');?>:</div><?php echo  $form->subject->setValue($message['theme'])?></div>
                        <div class="formRow clearfix">
                            <div class="label"><?php echo $this->translate('text');?>:</div><?php echo $form->content->setValue($message['text']); ?></div>
                        <div class="buttonsRow clearfix">
                            <?php echo $form->sendbutton?>
                        </div>
                    </div>
                </form>
            </div>
            <!-- END shadowSeparatorBox -->
        </div>
        <!-- END shadowSeparator -->
    </div>
    <!-- END messageTab -->