<?php $messageActions = $this->messageActions; ?>
<?php $singleAction = $messageActions->singleactions; ?>
<?php $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName()?>
<?php echo $this->partial('partials/message.phtml')?>
<div class= "messageContent">
	<div class="messageButtons clearfix">
    	<span class="msgBtn createNew" onclick="document.location='/message/send/'">Create New</span>
    	<span class="msgBtn trash" onclick="massTrash('<?php echo $action ?>')">Move to Trash</span>
    	<span class="msgBtn archived" onclick="massArchive('<?php echo $action ?>')" >Move to Archived</span>
	</div>
    <div class = "userMessages">
    <table  class="">
<?php /*    <table  class="table table-striped table-hover"> 
	        <thead style="">
	        <tr>
	            <td> </td>
	            <td> Sender Name </td>
	            <td> Subject </td>
	            <td> Message </td>
	            <td> Action </td>
	        </tr>
	        </thead> */?>
	        <tbody>
	        <?php
	        if($this->messages){
	            foreach($this->messages as $message){
	                $singleAction->setAttrib('id', 'singleactions_' . $message['id']);
	                $singleAction->setAttrib('onchange', "messageAction(this.id, '{$action}')");
                    $classNew = '';
                    $isNew = '';
                    if($message['recipient_status'] == 0) {
                        $isNew = "?status=new";
                        $classNew = ' class="newMessage"';
                    }
	                echo '
	                    <tr>
	                        <td style="width:800px"><input type="checkbox" class="messageCheckboxes" value="' . $message['id'] . '">
                                <a href="/message/view/' . $message['id'] . $isNew . '">
                                    <span' . $classNew. '>'.$message['sender_id'].'</span>
                                    <span' . $classNew. '>'.$message['theme'].'</span>
                                    <span>'.$message['text'].'</span></a>
                                    <span><a href="/message/reply/message_id/' . $message['id'] . '/current_action/"'. $action .'>reply</a></span>
                                    <span><a href="/message/forward/message_id/' . $message['id'] . '/current_action/"'. $action .'>reply</a></span>
	                        </td>
	                    </tr>
	                    ';
	            }
	
	        }
	
	        ?>
	
	        </tbody>
	    </table>
	</div>
</div>
<style type="text/css">
    .userMessages .newMessage {
        font-weight: bold;
    }
</style>