<?php $messageActions = $this->messageActions; ?>
<?php $singleAction = $messageActions->singleactions; ?>
<?php $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName() ?>
<?php echo $this->partial('partials/message.phtml') ?>
<div id="mainContent" class="clearfix">
    <div class="messageTab">
        <div class="shadowSeparator clearfix">
            <div class="shadowSeparatorBox clearfix">
                <div class="messageButtons clearfix">
                    <a href="<?php echo $this->baseUrl() . '/message/send/'?>"><span class="button-2 createMessage">Create New</span></a>
                    <span class="button-2 trash" onclick="massDelete('<?php echo $action ?>', '<?php echo $this->baseUrl()?>')">Move to Trash</span>
                    <span class="button-2 archived" onclick="massArchive('<?php echo $action ?>', '<?php echo $this->baseUrl()?>')">Move to Archived</span>
                </div>
                <div class="userMessages">
                    <table class="">
                        <tbody>
                        <?php
                        if ($this->messages) {
                            foreach ($this->messages as $message) {
                                $singleAction->setAttrib('id', 'singleactions_' . $message['id']);
                                $singleAction->setAttrib('onchange', "messageAction(this.id, '{$action}')");
                                $classNew = '';
                                $isNew = '';
                                if ($message['recipient_status'] == 0) {
                                    $isNew = "/new";
                                    $classNew = ' class="newMessage"';
                                }
                                echo '
	                    <tr>
	                        <td style="width:800px"><input type="checkbox" class="messageCheckboxes" value="' . $message['id'] . '">
                                <a href="' . $this->baseUrl() . '/message/view/' . $message['id'] . $isNew . '">
                                    <span' . $classNew . '>' . $message['sender_id'] . '</span>
                                    <span' . $classNew . '>' . $message['theme'] . '</span>
                                    <span>' . $message['text'] . '</span></a>
                                    <span><a href="' . $this->baseUrl() . '/message/reply/message_id/' . $message['id'] . '/current_action/"'. $action .'>reply</a></span>
                                    <span><a href="' . $this->baseUrl() . '/message/forward/message_id/' . $message['id'] . '/current_action/"'. $action .'>reply</a></span>
	                        </td>
	                    </tr>
	                    ';
                            }

                        }

                        ?>

                        </tbody>
                    </table>
                </div><!-- END userMessages -->
            </div><!-- END shadowSeparatorBox -->
        </div><!-- END shadowSeparator -->
    </div><!-- END messageTab -->
</div><!-- END mainContent -->
<style type="text/css">
    .userMessages .newMessage {
        font-weight: bold;
    }

</style>