<?php $messageActions = $this->messageActions; ?>
<?php $singleAction = $messageActions->singleactions; ?>
<div class="accountWrapper row-fluid no-space">
    <div class="leftNavigation span2">
        <?php
        echo $this->navigation()
            ->menu()
            ->setMaxDepth(0)
            ->setUlClass('nav nav-tabs nav-stacked')
            ->render(new Aimya_Navigation($this->navigation()->findAllBy('tag', 'messageMenu', true)));
        ?>
    </div>
    <div class="tab-content" id="tab-1">
        <div class = "userRelations"><table  class="table table-striped table-hover">
            <thead style="background: #ccc">
            <tr>
                <td> </td>
                <td> Sender Name </td>
                <td> Subject </td>
                <td> Message </td>
                <td></td>
            </tr>
            </thead>
            <tbody>
            <?php
            if($this->messages){
                foreach($this->messages as $message){
                    $singleAction->setAttrib('id', 'singleactions_' . $message['id']);
                    $singleAction->setAttrib('onchange', 'messageAction(this.id)');
                    echo '<tr>
                    <td><input type="checkbox" id="' . $message['id'] . '"></td>
        <td>'.$message['sender_id'].'</td>
        <td>'.$message['theme'].'</td>
        <td>'.$message['out'].'</td>
        <td>'. $singleAction .'</td>
    </tr>';
                }

            }

            ?>

            </tbody>
        </table>
    </div>
</div>


