<?php echo $this->partial('partials/message.phtml')?>
<?php $message = $this->message; ?>
<?php $sender = $this->sender; ?>
<?php ?>
<?php $form = $this->form;?>
<div id="mainContent" class="clearfix">
    <div class="messageTab">
        <div class="shadowSeparator clearfix">
            <div class="shadowSeparatorBox clearfix">
	<form method="post" action="/message/reply/">
        <div class="sendMessageBox clearfix">
            <div class="formRow clearfix">
                <div class="label messageReplyInbox">To:</div> <?php echo $form->message_id->setValue(Zend_Controller_Front::getInstance()->getRequest()->getParam('message_id'));?>
                <?php echo $form->username->setValue($sender['username']);?></div>
            <div class="formRow clearfix">
                <div class="label">Subject:</div><?php echo  $form->subject->setValue($message['theme'])?></div>
            <div class="formRow clearfix">
                <div class="label">Text:</div><?php echo $form->content->setValue($message['text']); ?></div>
            <div class="buttonsRow clearfix">
                <?php echo $form->sendbutton?>
            </div>
        </div>
	</form>
            </div>
            <!-- END shadowSeparatorBox -->
        </div>
        <!-- END shadowSeparator -->
    </div>
    <!-- END messageTab -->
</div>
<!-- END mainContent -->