<?php $form = $this->form;?>
<div class="tabbable tabs-left" id="left_tabs">
    <ul class="nav nav-tabs">
        <li><a href="#tab-1">Inbox</a></li>
        <li><a href="/message/archived">Archived</a></li>
        <li><a href="/message/sent">Sent</a></li>
        <li><a href="/message/trash">Trash</a></li>
        <li><a href="#tab-5">create</a></li>
    </ul>
    <div class="tab-content" id="tab-5">
        <form method="post" action="/message/send/">
            <table width="300px">
                <tr>
                    <td>
                        <?php echo $form->recipientid?>
                    </td>
                </tr>
                <tr>
                    <td>
                        To
                    </td>
                    <td>
                        <?php echo $form->email?>
                    </td>
                </tr>
                <tr>
                    <td>
                        Subject
                    </td>
                    <td>
                        <?php echo $form->subject?>
                    </td>
                </tr>
                <tr>
                    <td>
                        Content
                    </td>
                    <td>
                        <?php echo $form->content?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $form->sendbutton?>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>