<?php echo $this->partial('partials/message.phtml') ?>
<?php $form = $this->form; ?>
<div id="mainContent" class="clearfix">
    <div class="messageTab">
        <div class="messageButtons clearfix">
            <span class="msgBtn">Create New Message</span>
        </div>
        <form method="post" action="/message/send/">
            <table width="300px">
                <tr>
                    <td>To</td>
                    <td><?php echo $form->username?></td>
                </tr>
                <tr>
                    <td>Subject</td>
                    <td><?php echo $form->subject?></td>
                </tr>
                <tr>
                    <td>Content</td>
                    <td><?php echo $form->content?></td>
                </tr>
                <tr>
                    <td><?php echo $form->sendbutton?></td>
                </tr>
            </table>
        </form>
    </div>
</div>