<?php $messageActions = $this->messageActions; ?>
<?php $singleAction = $messageActions->singleactions; ?>
<?php $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName()?>
<div class="rightBlockProfile span8">
    <?php echo $this->partial('partials/layout.phtml')?>
    <div class="tab-content" id="tab-1">
        <div class = "userRelations"><table  class="table table-striped table-hover">
            <thead style="background: #ccc">
            <tr>
                <td> </td>
                <td> Sender Name </td>
                <td> Subject </td>
                <td> Message </td>
                <td></td>
            </tr>
            </thead>
            <tbody>
            <?php
            if($this->messages){
                foreach($this->messages as $message){
                    $singleAction->setAttrib('id', 'singleactions_' . $message['id']);
                    $singleAction->setAttrib('onchange', "messageAction(this.id, '{$action}')");
                    echo '<tr>
                    <td><input type="checkbox" id="' . $message['id'] . '"></td>
        <td>'.$message['sender_id'].'</td>
        <td>'.$message['theme'].'</td>
        <td>'.$message['text'].'</td>
        <td>'. $singleAction .'</td>
    </tr>';
                }

            }

            ?>

            </tbody>
        </table>
    </div>
</div>


