<?php $messageActions = $this->messageActions; ?>
<?php $singleAction = $messageActions->singleactions; ?>
<?php $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName() ?>
<?php echo $this->partial('partials/message.phtml') ?>
<div id="mainContent" class="clearfix">
    <div class="messageTab">
        <div class="shadowSeparator clearfix">
            <div class="shadowSeparatorBox clearfix">
                <div class="messageButtons clearfix">
                    <div class="messageButtons clearfix">
                        <span class="button-2 trash" onclick="massDelete('<?php echo $action ?>', '<?php echo $this->baseUrl()?>')">Move to Trash</span>
                        <span class="button-2 archived" onclick="massArchive('<?php echo $action ?>', '<?php echo $this->baseUrl()?>')">Move to Archived</span>
                    </div>
                    <div class="userMessages">
                        <table class="">
                            <tbody>
                            <?php
                            if ($this->messages) {
                                foreach ($this->messages as $message) {
                                    $originalTime = $message['created_at'];
                                    $time = date("H:i", strtotime($originalTime));
                                    $singleAction->setAttrib('id', 'singleactions_' . $message['id']);
                                    $singleAction->setAttrib('onchange', "messageAction(this.id, '{$action}')");
                                    echo '
	                    <tr>
	                        <td style="width:804px"><input type="checkbox" class="messageCheckboxes" value="' . $message['id'] . '">
                                <a href="' . $this->baseUrl() . '/message/view/' . $message['id'] . '">
                                    <span class =" messageSender">' . $message['sender_id'] . '</span>
                                    <span class =" messageTheme">' . $message['theme'] . '</span>
                                    <span class = "messageText">' . $message['text'] . '</span></a>

                                    <div class = "rightMessageBlock">
                                        <span class = "messageTime">' . $time . '</span>
                                        <a href="' . $this->baseUrl() . '/message/reply/message_id/' . $message['id'] . '/current_action/"'. $action .'><span class="messageReply"></span></a>
                                        <a href="' . $this->baseUrl() . '/message/forward/message_id/' . $message['id'] . '/current_action/"'. $action .'><span class="messageForward"></span></a>
                                    </div>

	                    </tr>
	                    ';
                                }

                            }

                            ?>

                            </tbody>
                        </table>
                    </div>
                    <!-- END userMessages -->
                </div>
                <!-- END shadowSeparatorBox -->
            </div>
            <!-- END shadowSeparator -->
        </div>
        <!-- END messageTab -->
    </div>
    <!-- END mainContent -->



