<?php $messageActions = $this->messageActions; ?>
<?php $singleAction = $messageActions->singleactions; ?>
<?php $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName()?>
<?php echo $this->partial('partials/message.phtml')?>
<div class= "messageContent">
	<div class="messageButtons clearfix">
    	<span class="msgBtn trash" onclick="document.location='/message/send/'">Move to Trash</span>
    	<span class="msgBtn archived" onclick="document.location='/message/send/'">Move to Archived</span>
	</div>
    <div class = "userRelations">
<?php //    <table  class="table table-striped table-hover"> ?>
		<table  class="">
	        <thead style="">
	        <tr>
	            <td> </td>
	            <td> Recipient Name </td>
	            <td> Subject </td>
	            <td> Message </td>
	            <td> Action </td>
	        </tr>
	        </thead>
	        <tbody>
	        <?php
	        if($this->messages){
	            foreach($this->messages as $message){
	                $singleAction->setAttrib('id', 'singleactions_' . $message['id']);
	                $singleAction->setAttrib('onchange', "messageAction(this.id, '{$action}')");
	                echo '
	                <tr>
	                    <td><input type="checkbox" id="' . $message['id'] . '"></td>
	                    <td>'.$message['recipient_id'].'</td>
	                    <td>'.$message['theme'].'</td>
	                    <td>'.$message['text'].'</td>
	                    <td>'. $singleAction .'</td>
	                </tr>';
	            }
	
	        }
	
	        ?>
	
	        </tbody>
	    </table>
	</div>
</div>



