<?php $messageActions = $this->messageActions; ?>
<?php echo $this->partial('partials/message.phtml') ?>
<div id="mainContent" class="clearfix">
    <div class="messageTab">
        <div class="messageButtons clearfix">
            <span class="msgBtn archived" onclick="document.location='/message/send/'">Move to Archived</span>
            <span class="msgBtn inbox" onclick="document.location='/message/send/'">Move to Inbox</span>
            <span class="msgBtn delete" onclick="document.location='/message/send/'">Delete</span>
        </div>
        <div class="userMessages">
            <table class="">
                <?php /*    <table  class="table table-striped table-hover">
	        <thead style="">
	        <tr>
	            <td> </td>
	            <td> Sender Name </td>
	            <td> Subject </td>
	            <td> Message </td>
	            <td> Action </td>
	        </tr>
	        </thead> */?>
                <tbody>
                <?php
                if ($this->messages) {
                    foreach ($this->messages as $message) {
                        echo '<tr>
	                <td><input type="checkbox" id="' . $message['id'] . '"></td>
	    <td>' . $message['sender_id'] . '</td>
	    <td>' . $message['theme'] . '</td>
	    <td>' . $message['text'] . '</td>
	</tr>';
                    }

                }

                ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

