<?php $messageActions = $this->messageActions; ?>
<?php echo $this->partial('partials/message.phtml')?>
<div class="tab-content" id="tab-1">
    <div class = "userRelations"><table  class="table table-striped table-hover">
        <thead style="background: #ccc">
        <tr>
            <td> </td>
            <td> Sender Name </td>
            <td> Subject </td>
            <td> Message </td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        <?php
        if($this->messages){
            foreach($this->messages as $message){
                echo '<tr>
                <td><input type="checkbox" id="' . $message['id'] . '"></td>
    <td>'.$message['sender_id'].'</td>
    <td>'.$message['theme'].'</td>
    <td>'.$message['text'].'</td>
</tr>';
            }

        }

        ?>

        </tbody>
    </table>
</div>



