<?php echo $this->partial('partials/message.phtml') ?>
<?php $message = $this->message ?>
<?php $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName() ?>
<?php $user = $this->user ?>
    <div class="messageTab viewMessageBlock">
        <div class="shadowSeparator clearfix">
            <div class="shadowSeparatorBox clearfix">
                <div class="formRow clearfix viewSender"><span class = "messageViewSender"><?php echo $user['firstname'] . ' ' . $user['lastname']?></span><div class="messageTime view"><?php echo $message['created_at']?></div></div>
                <div class="formRow clearfix viewTheme"><span class = "messageViewTheme"><?php echo $message['theme']?></span></div>
                <div class="formRow clearfix viewText"><span class = "messageViewText"><?php echo $message['text']?></span></div>
                <div class="buttonRow clearfix viewReply">  <a href="<?php echo  $this->baseUrl() . '/message/reply/message_id/' . $message['id'] . '/current_action/"'. $action .'>';?><span class="messageReply"></span></a></div>

            </div>
            <!-- END shadowSeparatorBox -->
        </div>
        <!-- END shadowSeparator -->
    </div>
    <!-- END messageTab -->