<!DOCTYPE html>
<html>
<head>

    <meta CHARSET="UTF-8">
    <title></title>
    <?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->addHelperPath("ZendX/JQuery/View/Helper", "ZendX_JQuery_View_Helper");
    ?>
    <?php  echo $this->jQuery(); ?>
    <?php $this->headLink()->appendStylesheet('/twitter/css/bootstrap.css');?>
    <?php $this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css');?>
    <?php $this->headScript()->appendFile('/js/jquery/jquery-ui-1.9.1.custom.min.js');?>
    <?php $this->headScript()->appendFile('/js/jquery/cookieJquery.js');?>
    <?php #$this->headScript()->appendFile('/js/jquery/jquery.uploadifive.js');?>
    <?php $this->headScript()->appendFile('/js/jquery/main.js');?>
    <?php $this->headLink()->appendStylesheet('/css/style.css');?>
    <?php $this->headScript()->appendFile('/twitter/js/bootstrap.js');?>

    <?php echo $this->headScript();?>
    <?php echo $this->headLink();?>
</head>
<body>
<!-- HEADER & NAVIGATION -->
<div class="row-fluid headerInside">
    <div class="span2 offset1">
        <div class="logo">
            <a href="index"><div class = "smallLogoImg"></div></a>
        </div>
    </div>


    <!-- /span3 -->

    <div class="span9" >
        <nav id="globalNav">
            <ul>
                <li><a href="#">HOME</a></li>
                <li><a href="#">PRIVACY POLICY</a></li>
                <li><a href="#">ABOUT AIMYA</a></li>
                <li><a href="#">HELP</a></li>
                <li><a href="/user/logout/">SIGN OUT</a></li>

            </ul>
        </nav>
    </div>

</div>


<?php
//information in left block of account:
//  firstname, lastname, avatar, member since
$identity = Zend_Auth::getInstance()->getStorage()->read();
$userModel = new Application_Model_DbTable_Users();
$profileModel = new Application_Model_Profile();

$username = $userModel->getUser($identity->id);
$avatarPath = $profileModel->getAvatarPath($identity->id); //path to avatar
$role = ($username['role'] == '1' ? 'Student' : 'Instructor');
if (Zend_Registry::isRegistered('username')) {
    $username = Zend_Registry::get('username');
} else {

    $username = "{$username['firstname']} {$username['lastname']}";
    Zend_Registry::set('username', $username);
}
?>
<div class ="fill">
    <div class="accountWrapper row-fluid no-space">

        <div class="leftBlockProfile span2">
            <div class ="profileTab">
                <h3> <?php echo $username;?></h3>
                <h5> <?php echo $role;?></h5>
                <div class="leftNavPhoto"><img src="<?php echo $avatarPath;?>"><br></div>
                No rate
                <div class="leftNavigation">
                    <?php
                    echo $this->navigation()
                        ->menu()
                        ->setMaxDepth(0)
                        ->setUlClass('nav nav-tabs nav-stacked')
                        ->render(new Aimya_Navigation($this->navigation()->findAllBy('tag', 'leftMenu', true)));
                    ?>
                </div>
            </div>
        </div>
        <div class="rightBlockProfile span10">
            <div class="mainBlockProfile span10">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
</div>
</body>
</html>