<!DOCTYPE html>
<html>
<head>

    <meta CHARSET="UTF-8">
    <title></title>
    <?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->addHelperPath("ZendX/JQuery/View/Helper", "ZendX_JQuery_View_Helper");
    ?>
    <?php  echo $this->jQuery(); ?>
    <?php $this->headLink()->appendStylesheet('/twitter/css/bootstrap.css');?>
    <?php $this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css');?>
    <?php $this->headScript()->appendFile('/js/jquery/jquery-ui-1.9.1.custom.min.js');?>
    <?php $this->headScript()->appendFile('/js/jquery/cookieJquery.js');?>
    <?php #$this->headScript()->appendFile('/js/jquery/jquery.uploadifive.js');?>
    <?php $this->headScript()->appendFile('/js/jquery/main.js');?>
    <?php $this->headLink()->appendStylesheet('/css/style.css');?>
    <?php $this->headScript()->appendFile('/twitter/js/bootstrap.js');?>

    <?php echo $this->headScript();?>
    <?php echo $this->headLink();?>
</head>
<body>

<?php
//information in left block of account:
//  firstname, lastname, avatar, member since, services
$identity = Zend_Auth::getInstance()->getStorage()->read();
$userModel = new Application_Model_DbTable_Users();
$profileModel = new Application_Model_Profile();
$servicesModel  = new Application_Model_DbTable_ServiceDetail();
$services = $servicesModel->getServiceByUser($identity->id);
$username = $userModel->getUser($identity->id);
$avatarPath = $profileModel->getAvatarPath($identity->id); //path to avatar
$role = ($username['role'] == '1' ? 'Student' : 'Instructor');
if (Zend_Registry::isRegistered('username')) {
    $username = Zend_Registry::get('username');
} else {

    $username = "{$username['firstname']} {$username['lastname']}";
    Zend_Registry::set('username', $username);
}
?>

    <div class="accountWrapper row-fluid no-space">

        <!-- HEADER & NAVIGATION -->
        <div class="row-fluid headerInside">
            <div class="headerAccount">
                <div class="logo">
                    <a href="index">
                        <div class="smallLogoImg"></div>
                    </a>
                </div>
                <input id="user_activity" type="hidden" value="1">

                <!-- /span3 -->

                <nav id="globalNav">
                    <ul>
                        <li><a href="#">HOME</a></li>
                        <li><a href="#">PRIVACY POLICY</a></li>
                        <li><a href="#">ABOUT AIMYA</a></li>
                        <li><a href="#">HELP</a></li>
                        <li><a href="/user/logout/">SIGN OUT</a></li>

                    </ul>
                </nav>
            </div>
        </div>
        <div class="accountContent clearfix">
            <div class="accountPage">
                <div class="messages">
                    <?php echo $this->flashMessages();?>
                </div>
                <div class="leftBlockProfile span2">
                    <div class="profileTab">
                        <h3> <?php echo $username;?></h3>
                        <h5> <?php echo $role;?></h5>

                        <div class = "leftNavPhoto"><img src="<?php echo $avatarPath;?>"><br></div>
                        <div class = "leftServices">
                            <?php
                            if($services){
                                foreach($services as $value){
                                    echo '$ '.$value['rate']. ' / ' .$value['duration'] . '  ' . $value['subcategory'].'<br>';
                                }
                            }
                            ?>
                        </div>
                        <div class="leftNavigation">
                            <?php
                            echo $this->navigation()
                                ->menu()
                                ->setMaxDepth(0)
                                ->setUlClass('nav nav-tabs nav-stacked')
                                ->render(new Aimya_Navigation($this->navigation()->findAllBy('tag', 'leftMenu', true)));
                            ?>
                        </div>
                    </div>
                    <div class="leftNavFooter">
                        <br> Copyright 2012 Aimya
                        <br> Created by Svitla.com
                    </div>
                </div>
                <div class="rightBlockProfile span8">
                    <div class="mainBlockProfile">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>
        </div>
</div>
</body>
</html>