<?php echo $this->partial('partials/adminNav.phtml') ?>
<div class="mainContainer userRelationsTab admin clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">

            <div class="deleteList">
                <table>
                    <thead>
                    <tr>
                        <td><?php echo $this->translate('№') ?></td>
                        <td><?php echo $this->translate('name') ?></td>
                        <td><?php echo $this->translate('uri') ?></td>
                        <td><?php echo $this->translate('language') ?></td>
                        <td><?php echo $this->translate('edit') ?></td>
                        <td><?php echo $this->translate('delete') ?></td>
                    </tr>
                    </thead>
                    <?php

                    foreach ($this->list as $key => $value) {

                        echo '<tr>';
                        echo '<td>' . $value['id'] . '</td>'
                            . '<td>' . $value['name'] . '</td>'
                            . '<td>' . $value['uri'] . '</td>'
                            . '<td>' . $value['language'] . '</td>'
                            . '<td><a href = "' . $this->baseUrl() . '/cms/edit/id/' . $value['id'] . '" class ="button-2 edit">edit</a></td>'
                            . '<td><a href = "' . $this->baseUrl() . '/cms/delete/id/' . $value['id'] . '" class ="button-2 delete">delete</a></td>';
                        echo '</tr>';

                    }

                    ?>
                </table>
                <a href="<?php echo $this->baseUrl() ?>/cms/new" class="button-2 add floatRight">add new</a>
            </div>
        </div>
    </div>
</div>