<div class = "deleteList">
    <table border = "1" cellpadding="5" cellspacing="5">
        <tr>
            <td>№</td><td>Name</td><td>Uri</td><td>Edit</td><td>Delete</td>
        </tr>
        <?php

        foreach($this->list as $key => $value){

            echo '<tr>';
                echo '<td>' . $value['id'] . '</td>'
                    .'<td>' . $value['name'] . '</td>'
                    .'<td>' . $value['uri'] . '</td>'
                    .'<td><a href = "/cms/edit/id/'.$value['id'].'">edit</a></td>'
                    .'<td><a href = "/cms/delete/id/'.$value['id'].'">delete</a></td>';
            echo '</tr>';

        }

        ?>
    </table>
    <a href = "/cms/new">Add new</a>
</div>