<div class="wrapperFull">
    <div class="main_content">



        <div class="breadcrumb"><a href="/index/index">Home</a>Error page</div>

        <div class="page_title">Oops! Page not found</div>

        <div class="not_found">
            <strong>The page you were looking for doesn’t exist.</strong><br />You may have mistyped the address or the page may have moved. Please start from the <a href="index">home page</a> or use the browser’s “Back” button. If you reached this page from another part of <strong>AppResume</strong>, please <a href="#">contact us</a> so we can correct mistake.<br />
            <br />
            Here are some things you might find helpful:
            <p>Go back on the <a href="index">Homepage</a> and try again</p>
            <!-- <p>Browse our <a href="sitemap">Sitemap</a> to see all the pages on our website</p> -->
            <p>Follow us on <a href="#">Twitter</a> or <a href="#">Facebook</a> for the latest updates and status.</p>
        </div>

</div>