<div class="searchTab mainContainer clearfix">

    <?php $hits = $this->hits; ?>
    <h1><?php echo "Search results for: \"{$_GET['search_string']}\""?></h1>

    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <div class="messageContent">
                <?php if (count($hits)): ?>
                <?php foreach ($hits as $hit) { ?>
                    <div class="searchItem">
                        <ul class="featuredInfo clearfix">
                            <li class="clearfix">
                                <span class="title"><?php echo $this->translate('Service name:') ?></span>

                                <div class="featuredTxt"><?php echo  ' ' . $hit->subcategory;?></div>
                            </li>
                            <li class="clearfix">
                                <span class="title"><?php echo $this->translate('Service category:') ?></span>

                                <div class="featuredTxt"><?php echo  ' ' . $hit->lesson_category;?></div>
                            </li>
                        </ul><br>


                        <a href="<?php echo "/user/" . $hit->user_id ?>">Read more…</a>

                        <div class="shadowSeparatorBoxSmall clearfix">
                        </div>
                        <div class="shadowSeparator clearfix">
                        </div>

                    </div>
                    <?php
                }?>
                <div class="feauteresButtons clearfix">
                    <input class ="showMore button-2 more" type="button" value = "<?php echo $this->translate('VIEW MORE') ?>">
                    </div><!--End feauteresButtons-->

                <?php else: ?>
                <?php echo "Your search returns no results." ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>