<div class="searchTab mainContainer clearfix">

    <?php $hits = $this->users; ?>

    <?php $profileModel = new Application_Model_Profile(); ?>
    <h1><?php echo "Search results for: \"{$_GET['search_string']}\""?></h1>

    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <div class="messageContent">
                <?php if (count($hits)): ?>
                <?php foreach ($this->users as $person): ?>
<!--                    --><?php //Zend_Debug::dump($person)?>
                <div class="shadowSeparator clearfix">
                    <div class="shadowSeparatorBoxSmall clearfix">
                        <div class="featureItem clearfix">

                            <?php $avatarPath = $profileModel->getAvatarPath($person['id'], 'medium') ?>
                            <div class="imageBlock boxShadow"><img src="<?php echo $avatarPath;?>"></div>
                            <div class="featuredButtonsTop clearfix">

                                <?php echo '<a class ="button-2 view viewProfile" href="' . $this->baseUrl() . '/user/' . $person['id'] . '">VIEW PROFILE</a>'; ?>

                                <?php echo '<input type="hidden" value = "' .$person["id"]. '">';?>

                            </div><!--End featuredButtonsTop-->
                            <ul class="featuredInfo">
                                <li class="clearfix">
                                    <span class="title"><?php echo $this->translate('Name:') ?></span>
                                    <div class="featuredTxt"><?php echo  ' ' .$person['firstname'] . ' ' . $person['lastname'];?></div>
                                </li>

                                <li class="clearfix">
                                    <span class="title"><?php echo $this->translate('Time zone:') ?></span>
                                    <div class="featuredTxt"><?php echo ' UTC ' . $person['timezone'];?></div>
                                </li>

                                <?php if (count($person['services']) > 0):?>
                                <li class="clearfix">
                                    <span class="title"><?php echo $this->translate('Services:') ?></span>
                                    <div class="featuredTxt">
                                        <?php
                                        $i = 0;
                                        foreach ($person['services'] as $index => $service) {
                                            echo $service['subcategory'];
                                            if(count($person['services']) - 1 != $i) echo ', ';
                                            $i++;
                                        }
                                        ?>
                                    </div>
                                </li>
                                <?php endif; ?>
<!--                                --><?php //if (count($person['service_requested']) > 0):?>
<!--                                <li class="clearfix">-->
<!--                                    <span class="title">--><?php //echo $this->translate('Service requested:') ?><!--</span>-->
<!--                                    <div class="featuredTxt">-->
<!--                                        --><?php
//                                        $i = 0;
//                                        foreach ($person['service_requested'] as $index => $service) {
//                                            echo $service['subcategory'];
//                                            if(count($person['service_requested']) - 1 != $i) echo ', ';
//                                            $i++;
//                                        }
//                                        ?>
<!--                                    </div>-->
<!--                                </li>-->
<!--                                --><?php //endif; ?>
                                <?php if (count($person['add_info']) > 0):?>
                                <li class="clearfix">
                                    <span class="title"><?php echo $this->translate('About me:') ?></span>
                                    <div class="featuredTxt more"><?php echo $person['add_info'];?></div>
                                </li>
                                <?php endif; ?>
                            </ul><!--End featuredInfo -->

                        </div><!--End featureItem -->
                    </div><!--End shadowSeparatorBox-->
                </div><!--End shadowSeparator-->


                <?php endforeach; ?>
                <div class="feauteresButtons clearfix">
                    <input class ="showMore button-2 more" type="button" value = "<?php echo $this->translate('VIEW MORE') ?>">
                    </div><!--End feauteresButtons-->

                <?php else: ?>
                <?php echo "Your search returns no results." ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {

        $(".more").shorten({
            "showChars" : 200
        });

    });
</script>
