<div class="mesage-header" align="right">
    <input type='button' class="btn" onclick="document.location='/message/send/'" value="Create New">
</div><br>
<div class="leftMessageNavigation span2">
    <?php
    echo $this->navigation()
        ->menu()
        ->setMaxDepth(0)
        ->setUlClass('nav nav-tabs nav-stacked')
        ->render(new Aimya_Navigation($this->navigation()->findAllBy('tag', 'messageMenu', true)));
    ?>
</div>



