<div class="resumeFooter">
    <div class="buttonRow clearfix">
        <input type="button" class="button save" value="<?php echo $this->translate('preview in pdf');?>" onClick="window.open('<?php echo $this->baseUrl().'/resume/pdf/';?>')">
        <input type="button" class="button save" value="<?php echo $this->translate('preview online');?>" onClick="window.open('<?php echo $this->baseUrl().'/resume/online/';?>')">
        <input type="button" class="button save" value="<?php echo $this->translate('download pdf');?>" onClick="window.open('<?php echo $this->baseUrl().'/resume/download/';?>')">
    </div>
</div>