<div class="resumeFooter">
    <div class="buttonRow clearfix">
        <input type="button" class="button save" value="preview in pdf" onClick="window.open('<?php echo $this->baseUrl().'/resume/pdf/';?>')">
        <input type="button" class="button save" value="preview online" onClick="window.open('<?php echo $this->baseUrl().'/resume/online/';?>')">
        <input type="button" class="button save" value="download pdf">
    </div>
</div>