<?php echo $this->partial('partials/adminNav.phtml') ?>
<div class="mainContainer admin clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">


            <div class="metricItem">
                <h1><?php echo $this->translate('users:')?></h1>
                <div class="formRow"><span class="head"><?php echo $this->translate('total users:')?></span><?php echo $this->usersCount['allTime']['total'];?></div>
                <div class="formRow"><span class="head"><?php echo $this->translate('teachers:')?></span><?php echo $this->usersCount['allTime']['teachers'];?></div>
                <div class="formRow"><span class="head"><?php echo $this->translate('students:')?></span><?php echo $this->usersCount['allTime']['students'];?></div>
            </div>
            <div class="shadowSeparatorBoxSmall"> </div>
            <div class="shadowSeparator"> </div>
            <div class="metricItem">
                <h1><?php echo $this->translate('joined last month:')?></h1>
                <div class="formRow"><span class="head"><?php echo $this->translate('total users:')?></span><?php echo $this->usersCount['lastMonth']['total'];?></div>
                <div class="formRow"><span class="head"><?php echo $this->translate('teachers:')?></span><?php echo $this->usersCount['lastMonth']['teachers'];?></div>
                <div class="formRow"><span class="head"><?php echo $this->translate('students:')?></span><?php echo $this->usersCount['lastMonth']['students'];?></div>
            </div>
            <div class="shadowSeparatorBoxSmall"> </div>
            <div class="shadowSeparator"> </div>
            <div class="metricItem">
                <h1><?php echo $this->translate('aimya income:')?></h1>
                <div class="formRow"><span class="head"><?php echo $this->translate('year to date:')?></span></div>
                <div class="formRow"><span class="head"><?php echo $this->translate('month to date:')?></span></div>
            </div>
            <div class="shadowSeparatorBoxSmall"> </div>
            <div class="shadowSeparator"> </div>
            <div class="metricItem">
                <h1><?php echo $this->translate('lessons:')?></h1>
                <div class="formRow"><span class="head"><?php echo $this->translate('this year:')?></span></div>
                <div class="formRow"><span class="head"><?php echo $this->translate('last month:')?></span></div>
            </div>


        </div>
    </div>
</div>