<?php echo $this->partial('partials/adminNav.phtml') ?>
<div class="mainContainer userRelationsTab usersAdmin admin clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <table class="table">
                <thead>
                <tr>
                    <td> <?php echo $this->translate('user') ?></td>
                    <td> <?php echo $this->translate('name') ?></td>
                    <td> <?php echo $this->translate('last name') ?></td>
                    <td> <?php echo $this->translate('role') ?></td>
                    <td> <?php echo $this->translate('member since') ?></td>
                    <td> <?php echo $this->translate('last payment') ?></td>
                    <td> <?php echo $this->translate('valid till') ?></td>
                    <td> <?php echo $this->translate('request for refund') ?></td>

                </tr>
                </thead>
                <tbody>
                <?php   $users = $this->userList;
                foreach ($users as $user): ?>

                    <?php //=Zend_Debug::dump($booking)?>
                <tr>
                    <td class="username">
                        <?php echo $user['username'];?>
                    </td>
                    <td class="name">
                        <?php echo $user['firstname'];?>
                    </td>
                    <td class="lastname">
                        <?php echo $user['lastname'];?>
                    </td>
                    <td class="role">
                        <?php if($user['role']==1){
                        $role='Student';
                    }
                    else{
                        $role='Instructor';
                    }
                        echo $role;?>
                    </td>
                    <td>
                        <?php echo date("d-m-Y", strtotime($user['created_at']));?>
                    </td>
                    <?php if($user['active_to']!=null){
                        $validTill = date("d-m-Y", strtotime($user['active_to']));
                        $lastPaid = date("d-m-Y", strtotime($user['updated_at']));
                    }else{
                    $lastPaid = '';
                    $validTill = '';
                }?>
                    <td><?php echo $lastPaid;?></td>
                    <td><?php echo $validTill;?></td>
                    <td class="suspend center">
                        <input type="button" class="button-2 refund" value ="refund" onclick="approveRefund(this);return false;">
                        <input type="button" class="button-2 delete" value ="cancel" onclick="cancelRefund(this);return false;">
                        <input type="hidden" value = "<?php echo $user['subscription_id'];?>">
                    </td>
                </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class = "usersAlert" id="cancel-unsubscribe" title="UNSUBSCRIBE:">
    <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>Unsubscribing isn't cool. Are you sure you want to proceed?</p>
</div>