<?php echo $this->partial('partials/adminNav.phtml') ?>
<div class="mainContainer  userRelationsTab usersAdmin admin clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">

            <table class="table">
                <thead>
                <tr>
                    <td> <?php echo $this->translate('user') ?></td>
                    <!--<td> <?php /*echo $this->translate('Status') */?></td>-->
                    <td> <?php echo $this->translate('name') ?></td>
                    <td> <?php echo $this->translate('last name') ?></td>
                    <td> <?php echo $this->translate('role') ?></td>
                    <td> <?php echo $this->translate('suspend') ?></td>

                </tr>
                </thead>
                <tbody>
                <?php   $users = $this->userList;
                foreach ($users as $user): ?>
                    <?php //Zend_Debug::dump($booking)?>
                <tr>
                    <td class="username">
                        <?php echo $user['username'];?>
                    </td>
                    <td class="name">
                        <?php echo $user['firstname'];?>
                    </td>
                    <td class="lastname">
                        <?php echo $user['lastname'];?>
                    </td>
                    <td class="role">
                    <?php if($user['role']==1){
                        $role='Student';
                    }
                        else{
                            $role='Instructor';
                        }
                        echo $role;?>
                    </td>
                    <td class="suspend center">
                        <?php if($user['status']==1){
                        echo '<input type="button" class="button-2 block" value ="suspend">';
                    }
                    else if($user['status']==2){
                        echo '<input type="button" class="button-2 unblock" value ="restore">';
                    }?>
                    </td>
                </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>