<script type="text/javascript">
    /*$(function() {
        $('#file_upload').uploadifive({
            'auto'         : false,
            'formData'     : {'experienceUpload' : 'certificate'},
            'queueID'      : 'queue',
            'uploadScript' : '/resume/upload',
            'onUploadComplete' : function(file, data) {
                console.log(data);
            }
        });
    });*/
</script>

<div class="resumeGeneral clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <div class="experienceList clearfix">
                <?php
                foreach ($this->experienceList as $value):?>
                    <div class="experienceItem clearfix">
                        <div class="headRow clearfix">
                            <h1>experience:</h1>
                            <div class="buttonRow clearfix">
                                <input type="button" value="edit" class="button-2 edit" onclick=editExperience(this);>
                                <input type="button" value="delete" class="button-2 delete" onclick=deleteExperience(this);>
                                <input type="hidden" value="<?php echo $value['id'];?>">
                            </div>
                        </div>
                        <div class="experienceBody clearfix">
                            <?php echo $value['content'];?>
                        </div>


                    </div>

                    <?php endforeach; ?>
            </div>
            <div class="experienceForm">
                <div>Add new experience:</div>
                <?php
                echo $this->experienceForm->getElement('experience');
                ?>
                <div id="queue"></div>
                <input id="file_upload" name="file_upload" type="file" multiple="true">

                <input type="button" value="save" class="btn" onclick=saveExperience();>
            </div>
        </div>

    </div>
    <?php echo $this->partial('partials/resumeFooter.phtml') ?>
</div>