<?php
foreach($this->experienceList as $value):?>
    <div class = "experienceItem">
        <div class = "experienceHeader">Experience : </div>
        <div class = "experienceBody">
            <?php echo $value['content'];?>
        </div>
        <input type = "button" value ="edit" class = "btn" onclick=editExperience(this);>
        <input type = "button" value ="delete" class = "btn" onclick=deleteExperience(this);>
        <input type = "hidden" value="<?php echo $value['id'];?>">
    </div>

<?php endforeach;?>
<div>Add new experience: </div>
<?php
echo $this->experienceForm->getElement('experience');
?>
<input type = "button" value ="save" class = "btn" onclick=saveExperience();>