<div class="resumeGeneral clearfix">

    <div class="shadowSeparatorBox clearfix">
        <div class="resumeList clearfix">
            <?php
            foreach ($this->experienceList as $value):?>
                <div class="shadowSeparator clearfix">
                    <div class="shadowSeparatorBot clearfix">
                        <div class="resumeItem clearfix">
                            <div class="headRow clearfix">
                                <h1>experience:</h1>

                                <div class="buttonRow clearfix">
                                    <input type="button" value="edit" class="button-2 edit"
                                           onclick="editResumeItem(this, 'experience');">
                                    <input type="button" value="delete" class="button-2 delete"
                                           onclick="deleteResumeItem(this, 'experience');">
                                    <input type="hidden" value="<?php echo $value['id'];?>">
                                </div>
                            </div>
                            <div class="resumeItemBody clearfix">
                                <?php echo $value['content'];?>
                            </div>
                        </div>
                    </div>
                </div>

                <?php endforeach; ?>
        </div>
        <div class="buttonsRow clearfix">
            <input type="button" class="button-2 add addResumeItem floatRight" value="add experience"
                   onclick="addResumeItem();">
        </div>
        <div class="resumeItemForm">
           <h1>Add new experience:</h1>
            <div class="formRow clearfix">
                <?php
                echo $this->experienceForm->getElement('experience');
                ?>
            </div>
            <div class="uploadWrapper">
                <div id="queue"></div>
                <input id="file_upload" name="file_upload" type="file" multiple="true">
                <input id="uploadExperience" class="button-2 upload" type="button" value="upload file"
                       onclick=uploadExperienceFile();>
                <input type="button" value="save" class="button-2 save floatRight"
                       onclick="saveResumeItem('experience');">
            </div>
        </div>
    </div>


    <?php echo $this->partial('partials/resumeFooter.phtml') ?>
</div>