<div id="tabs" class="tabsHolder clearfix">
    <div id="tabsNavigation" class="clearfix">
        <ul>
            <li><a href="#tabs-1">basic</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/resume/objective">objective</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/resume/experience">experience</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/resume/education">education</a></li>
            <li><a href="<?php echo $this->baseUrl()?>/resume/skills">skills</a></li>
        </ul>
    </div>
    <!--End tabsNavigation-->
    <div class="mainContainer clearfix">
        <div id="tabs-1" class="clearfix">
            <div class="resumeGeneral">
                <div class="shadowSeparator clearfix">
                    <div class="shadowSeparatorBox clearfix">
                        <div class="avatarBox floatLeft">
                            <img class="resumePhoto" src="<?php echo $this->avatarPath;?>">
                        </div>
                        <div class="infoBox floatLeft">

                            <ul class = "userInfo">
                                <?php $gender = 'male';
                                if ($this->profile['gender'] == 'female') $gender = 'female'; ?>
                                <li class = "userName"><?php echo $this->profile['firstname'] . ' ' . $this->profile['lastname'];?></li>
                                <?php if ($this->profile['birthday']) echo '<li class = "birthday">' . $this->profile["birthday"] . '</li>';?>
                                <?php if ($this->profile['gender']) echo '<li class = "gender ' .$gender .'">' . $this->profile["gender"] . '</li>';?>
                                <?php if ($this->profile['email']) echo '<li class = "mail">' . $this->profile["email"] . '</li>';?>
                                <?php if ($this->profile['language']) echo '<li class = "language">' . $this->profile["language"] . '</li>';?>
                                <?php if ($this->profile['education']) echo '<li class = "education">' . $this->profile["education"] . '</li>';?>
                                <?php if ($this->profile['degree']) echo '<li class = "degree">' . $this->profile["degree"] . '</li>';?>
                                <?php if ($this->profile['address']) echo '<li class = "address">' . $this->profile["address"] . '</li>';?>
                                <?php if ($this->profile['telephone']) echo '<li class = "phone">' . $this->profile["telephone"] . '</li>';?>
                            </ul>

                        </div>
                        <div class="buttonsRow floatRight">
                            <input type="button" class="button-2 edit" value="edit" onclick="editResume()";>
                            <input type="button" class="button-2 save saveResume" value="save" onclick="saveResume()";>
                        </div>
                    </div>
                    <!--End shadowSeparatorBox-->
                </div>
                <!--End shadowSeparator-->
                <?php echo $this->partial('partials/resumeFooter.phtml') ?>
            </div>
            <!--End profileGeneral-->

        </div>
        <!--End Tab-->

    </div>
    <!--End mainContainer-->

</div><!--End tabs-->



<?php print_r($this->errors); ?>