<div class="resumeGeneral clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <div class="headRow clearfix">
                <h1>describe objective:</h1>
                <div class="buttonRow">
                    <input type="button" class = "button-2 save" value="save" onclick=updateObjective();>
                </div>
            </div>
            <div class="formRow clearfix objective">
                <?php
                echo $this->objectiveForm->objective;
                ?>
            </div>
        </div>

    </div>
    <?php echo $this->partial('partials/resumeFooter.phtml') ?>
</div>