<div class="resumeGeneral clearfix">
    <div class="shadowSeparator clearfix">
        <div class="shadowSeparatorBox clearfix">
            <div class="headRow clearfix">
                <h1><?php echo $this->translate('describe objective');?>:</h1>

            </div>
            <div class="formRow clearfix objective">
                <?php
                echo $this->objectiveForm->objective;
                ?>
            </div>
            <div class="buttonRow">
                <input type="button" class = "button-2 save floatRight"  value="<?php echo $this->translate('save');?>" onclick=updateObjective();>
            </div>
        </div>

    </div>
    <?php echo $this->partial('partials/resumeFooter.phtml') ?>
</div>