<?php $this->headScript()->appendFile('/js/jquery/jquery.uploadifive.js');?>
<?php echo $this->headScript('skill');?>
<script type="text/javascript">
    uploadify('skill');

</script>

<div class="resumeGeneral clearfix">
    <div class="shadowSeparatorBox clearfix">
        <div class="experienceList clearfix">
            <?php
            foreach ($this->skillList as $value):?>
                <div class="shadowSeparator clearfix">
                    <div class="shadowSeparatorBot clearfix">
                        <div class="resumeItem clearfix">
                            <div class="headRow clearfix">
                                <h1>skill:</h1>

                                <div class="buttonRow clearfix">
                                    <input type="button" value="edit" class="button-2 edit"
                                           onclick="editResumeItem(this,'skill');">
                                    <input type="button" value="delete" class="button-2 delete"
                                           onclick="deleteResumeItem(this, 'skill')";>
                                    <input type="hidden" value="<?php echo $value['id'];?>">
                                </div>
                            </div>
                            <div class="resumeItemBody clearfix">
                                <?php echo $value['content'];?>
                            </div>


                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
        </div>
        <div class="buttonsRow clearfix">
            <input type="button" class="button-2 add addResumeItem floatRight" value="add skill"
                   onclick="addResumeItem();">
        </div>
        <div class="resumeItemForm">
            <h1>Add new skill:</h1>

            <div class="formRow clearfix">
                <?php
                echo $this->skillsForm->getElement('skill');
                ?>
            </div>
            <div class="uploadWrapper">

                <input id="file_uploadskill" type="file" name="file_upload" />
                <input type="button" value="save" class="button-2 save floatRight"
                       onclick="saveResumeItem('skill');">
            </div>
            <div id="queue"></div>
        </div>
    </div>
    <?php echo $this->partial('partials/resumeFooter.phtml');?>

</div>
