<div id="dialog-form" title="Booking">
    <?php echo $this->bookingForm;?>
</div>
    <input type = "button" id = "bookLesson" value = "book lesson">
<script type='text/javascript'>
    jQuery(document).ready(function() {
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        jQuery('#calendar').fullCalendar({
            editable: true,
            disableDragging:true,
            allDay:false,

            header:{
                left:   'title',
                center: ' agendaDay, month',
                right:  'today,  prev, next'
            },
            dayClick: function(date, allDay, jsEvent, view) {
//                $("#dialog-form").dialog( "open" );
//                $('#started_at').val(date);
               jQuery('#calendar').fullCalendar('changeView', 'agendaDay');
               jQuery('#calendar').fullCalendar('gotoDate', date);

            },
            eventClick: function(event, element) {
                var view =  jQuery('#calendar').fullCalendar('getView');
                if(view.name == 'agendaDay'){ // if clicked on event while in agendaDay

                    $("#dialog-form").dialog( "open" );
                    $('#started_at').val(event.start);
                    $('#focus_name').val(event.title);
                    $('#add_info').val(event.add_info);
                    $('#rate').val(event.rate);
                    $('#duration').val(event.duration);
                    $('#recipiend_id').val(event.recipient_id + "");

                }else{
                    jQuery('#calendar').fullCalendar('changeView', 'agendaDay');
                    jQuery('#calendar').fullCalendar('gotoDate', event.start);
                }

            },
            events: function(start, end, callback) {
                jQuery("body").append('<div class="loadingIcon"></div>');
                $.ajax({
                    cache: false,
                    url: 'booking/index',
                    success: function(msg) {
                        jQuery('.loadingIcon').remove();
                            var events = [];
                            for(var c = 0; c < msg.booking.length; c++){
                                events.push({
                                    title: msg.booking[c].focus_name,
                                    start: msg.booking[c].started_at,
                                    recipient_id:  msg.booking[c].recipient_id,
                                    add_info:  msg.booking[c].add_info,
                                    rate:  msg.booking[c].rate,
                                    duration:  msg.booking[c].duration,
                                    allDay: false
                                });
                            }
                            callback(events);

                    }
                });
            }


        });

//FORM DIALOG JQUERY

        $( "#dialog-form" ).dialog({
            autoOpen: false,
            height: 450,
            width: 400,
            modal: true,
            resizable:false,
            close: function() {

            }
        });



        $('#started_at').datetimepicker();

        $('#sendBooking').click(function(){
            $.post(

                "/booking/add/0/controller%3D%3Ebooking/1/action%3D%3Eadd", {
                    "recipient_id": $('#recipiend_id').val(),
                    "focus_name": $('#focus_name').val(),
                    "started_at" : $('#started_at').val(),
                    "duration" : $('#duration').val(),
                    "feedback":$('#feedback:checked').val()||0,
                    "video":$('#video:checked').val()||0,
                    "notes":$('#notes:checked').val()||0,
                    "rate" : $('#rate').val(),
                    "add_info" : $('#add_info').val()


                },
                function(response){
                    $('#calendar').fullCalendar('renderEvent',
                        {
                            title : $('#focus_name').val(),
                            start : $('#started_at').val(),
                            end   : $('#started_at').val()
                        });
                    $("#dialog-form").dialog( "close" );
                    $("#dialog-form form").get(0).reset();
                });

        return false;
        });
        $('#bookLesson').click(function(){

            $("#dialog-form").dialog( "open" );

        });
    });//END JQUERY





</script>

<div id='calendar'></div>

