<script type='text/javascript'>

    jQuery(document).ready(function() {

        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        jQuery('#calendar').fullCalendar({
            editable: true,
            header:{
                left:   'title',
                center: ' agendaDay, agendaWeek, month',
                right:  'today,  prev, next'
            },
            dayClick: function(date, allDay, jsEvent, view) {
                var event=prompt('New event');
                if(event)
                $('#calendar').fullCalendar('renderEvent',
                    {
                        title : event,
                        start : date,
                        end   : date
                    });
            },
            eventClick: function(event, element) {
                event.title = prompt('edit event', event.title);
                if(event.title)
                $('#calendar').fullCalendar('updateEvent', event);

            }


        });

    });

</script>
<div id='calendar'></div>